# Repopulation Paris

## First Look into Bottin Data

In [1]:
import pandas as pd
import geopandas as gpd

In [29]:
bottins = pd.read_csv("data/strict_addressing.csv")

In [30]:
print("size of table:", bottins.shape)
bottins.head(50)

size of table: (4406164, 8)

,Unnamed: 0,page,row,Nom,Métier,Rue,Numéro,annee
0,bpt6k6282019m,144,0,Aaron,bronzes,passage Choiseal,72 et 74.,1855
1,bpt6k6282019m,144,1,Aaron (Mic.),manuf. de porcelaines,Bondy,30.,1855
2,bpt6k6282019m,144,3,Abadie,architecte,Provence,7.,1855
3,bpt6k6282019m,144,5,Abadie,tabac et estamin.,Ménilmontant,158.,1855
4,bpt6k6282019m,144,6,Abanse,instituteur,Sts-Pères,30.,1855
5,bpt6k6282019m,144,7,Abat,rentier,Isly,10.,1855
6,bpt6k6282019m,144,13,Abault et Coudray,charpentiers,Corbeau,23.,1855
7,bpt6k6282019m,144,14,Abault (Paul),libraire,quai des Angustins,9.,1855
8,bpt6k6282019m,144,15,Abavid,vins,Beaujolais-da-Temple,7.,1855
9,bpt6k6282019m,144,16,Abazaer (Are),cristaux et porcelaines,Pei.Ecuries,26.,1855
10,bpt6k6282019m,144,17,Abbadie (A.) et Montagnan,draps,Neuve-desBons-Enfants,1.,1855
11,bpt6k6282019m,144,20,Abbal,coiffeur,Parc-Royal,8.,1855
12,bpt6k6282019m,144,21,Abbatucci (Séverin),député de la Corse,place Vendôme,11-13.,1855
13,bpt6k6282019m,144,24,Abbatucci # (Th.),maître des requêtes au conseil d'Etat,pl. Vendôme,ll et 13.,1855
14,bpt6k6282019m,144,25,Abbaye-au-Bois (communauté del'),église succursale de St-Thomas-d'Aquin,Sèvres,16.,1855
15,bpt6k6282019m,144,26,Abeille,médecin,Pépinière,39.,1855
16,bpt6k6282019m,144,27,Abeille,propriét.,Faub.-St-Honoré,27.,1855
17,bpt6k6282019m,144,28,Abel,coutelier,Paradis-Poissonnière,59.,1855
18,bpt6k6282019m,144,29,Abel,coke et escarhilles,Austerlitz-St-Marcel,45.,1855
19,bpt6k6282019m,144,31,Abel de Pujol * (de l'Institut),peintre d'hist.,Albouy,14.,1855
20,bpt6k6282019m,144,32,Abel-Loroue,chemisier,Castiglione,4.,1855
21,bpt6k6282019m,144,33,Abel-Mouillard et E. Gaspart,fab. de châles et confections pour dames,boul. St-Denis,9.,1855
22,bpt6k6282019m,144,34,Abello,gainier-ébéniste,Temple,79.,1855
23,bpt6k6282019m,144,35,Aberlin,coiffeur,Montmartre,160.,1855
24,bpt6k6282019m,144,36,Abert,boulanger,Ecole-de-Médecine,04.,1855
25,bpt6k6282019m,144,37,Abette,tapissier,Pont-Louis-Philippe,13.,1855
26,bpt6k6282019m,144,38,Abillot,peintre-vitrier,Pépinière,82.,1855
27,bpt6k6282019m,144,39,Abit,bonnetier,boul. Bonne-Nouvelle,11.,1855
28,bpt6k6282019m,144,40,Abit jeune,propr.,St-Maar-Popincourt,158.,1855
29,bpt6k6282019m,144,41,Abler,cordonnier pour dames,St-Honoré,317.,1855
30,bpt6k6282019m,144,42,Aboire,ligeur de dessins,Fontaine-au-Roi,59,1855
31,bpt6k6282019m,144,43,Abonnet,vins,St-Jean-de-Beauvais,22.,1855
32,bpt6k6282019m,144,45,Abraham (E.),fabr. de broderies,NeuveSt-Eustache,44.,1855
33,bpt6k6282019m,144,47,Abraham,relieur,Parcheminerie,2.,1855
34,bpt6k6282019m,144,48,Abraham,vérific. des domaines,Martyrs,63.,1855
35,bpt6k6282019m,144,49,Abraham-Cliver (Edouard),cravates et foulards,Neape-St-Eustache,36.,1855
36,bpt6k6282019m,144,50,Abraham-Dubois *,conseiller-référ. à la cour descomptes,Cassette,7.,1855
37,bpt6k6282019m,144,51,Abrahams Junior (J.-D.),pierres fines,Bourse,1.,1855
38,bpt6k6282019m,144,52,Abran,bottler,Vingt-Neuf-Juillet,5.,1855
39,bpt6k6282019m,144,53,Abrial (Cte d'),avocat,Oudinot,22.,1855
40,bpt6k6282019m,144,55,Abry,ancien libraire,Basse-du-Rempart,56.,1855
41,bpt6k6282019m,144,56,Abry (J.),fab. de fleurs,Ste-Apolline,33.,1855
42,bpt6k6282019m,144,57,Absil (Mme),bandagiste,Mandar,4.,1855
43,bpt6k6282019m,144,58,Absire,tailleur,Chaillot,18.,1855
44,bpt6k6282019m,144,59,Abt (H.G.) fils et Cie,fab.de chapeaux de paille,Richelieu,79.,1855
45,bpt6k6282019m,144,60,Abt (Luc),fab.chapeaux de paille,Richelieu,64.,1855
46,bpt6k6282019m,144,65,Acar,premier pharmacien de l'Empereur,St-Honoré,313.,1855
47,bpt6k6282019m,144,66,Acard,fab. de champignons,Beaubourg,36.,1855
48,bpt6k6282019m,144,67,Acard,cordier,Mouffetard,280.,1855
49,bpt6k6282019m,144,68,Acard (Eugène),huissier,Richelieu,92.,1855

In [4]:
print("number of streets in dataset:", len(bottins["Rue"].unique()))

number of streets in dataset: 195464

In [5]:
bottins_original = bottins.copy()

## Paris Opendata - Voies

In [6]:
voies = pd.read_csv("data/opendata_voie_paris.csv", sep=";")

In [7]:
print("number of voies:", len(voies))
voies.head()

number of voies: 6542

,N_SQ_VO,C_COINSEE,C_DESI,C_LIAISON,L_VOIE,L_COURTMIN,L_LONGMIN,C_VOIE,B_FANTOIR,B_OFF,C_VOIE_VP,Geometry,OBJECTID,C_DOMOFF,N_SQ_CO,LENGTH,Geometry X Y
0,750004016,75056,IMP,NaN,BAUDRAN,Imp. Baudran,Impasse Baudran,750560733,O,O,0717,"{""coordinates"": [[2.3554518641916804, 48.82415...",6,O,750001537,64.625200,"48.82415332715383,2.3558919735528483"
1,750003821,75056,IMP,DES,CHEVALIERS,Imp. des Chevaliers,Impasse des Chevaliers,750561994,O,O,1986,"{""coordinates"": [[2.3960916096233094, 48.87258...",59,P,750001537,77.423197,"48.87229377669366,2.3963259349268453"
2,750005946,75056,RUE,DES,BONS VIVANTS,R. des Bons Vivants,Rue des Bons Vivants,750561106,O,O,1111,"{""coordinates"": [[2.346752283163513, 48.862212...",112,P,750001537,39.406151,"48.862044141078364,2.34682583693024"
3,750001312,75056,RUE,NaN,JEAN HUGUES,R. Jean Hugues,Rue Jean Hugues,750564899,O,O,4806,"{""coordinates"": [[2.274705254077503, 48.868429...",170,O,750001537,45.962263,"48.86861817275934,2.2748341164181163"
4,750005774,75056,RUE,NaN,JEAN-JACQUES ROUSSEAU,R. Jean-Jacques Rousseau,Rue Jean-Jacques Rousseau,750564901,O,O,4808,"{""coordinates"": [[[2.3396869374353004, 48.8620...",171,P,750001537,397.842033,"48.86347293952501,2.342392728552715"

In [8]:
#keep only columns that might be useful further on
voies = voies[["N_SQ_VO", "L_VOIE", "L_COURTMIN", "L_LONGMIN", "Geometry", "LENGTH", "Geometry X Y"]]
voies.head()

,N_SQ_VO,L_VOIE,L_COURTMIN,L_LONGMIN,Geometry,LENGTH,Geometry X Y
0,750004016,BAUDRAN,Imp. Baudran,Impasse Baudran,"{""coordinates"": [[2.3554518641916804, 48.82415...",64.625200,"48.82415332715383,2.3558919735528483"
1,750003821,CHEVALIERS,Imp. des Chevaliers,Impasse des Chevaliers,"{""coordinates"": [[2.3960916096233094, 48.87258...",77.423197,"48.87229377669366,2.3963259349268453"
2,750005946,BONS VIVANTS,R. des Bons Vivants,Rue des Bons Vivants,"{""coordinates"": [[2.346752283163513, 48.862212...",39.406151,"48.862044141078364,2.34682583693024"
3,750001312,JEAN HUGUES,R. Jean Hugues,Rue Jean Hugues,"{""coordinates"": [[2.274705254077503, 48.868429...",45.962263,"48.86861817275934,2.2748341164181163"
4,750005774,JEAN-JACQUES ROUSSEAU,R. Jean-Jacques Rousseau,Rue Jean-Jacques Rousseau,"{""coordinates"": [[[2.3396869374353004, 48.8620...",397.842033,"48.86347293952501,2.342392728552715"

In [9]:
# prepare data for alignment
bottins["Rue"] = bottins["Rue"].str.lower()
voies["L_VOIE"] = voies["L_VOIE"].str.lower()
voies["L_COURTMIN"] = voies["L_COURTMIN"].str.lower()
voies["L_LONGMIN"] = voies["L_LONGMIN"].str.lower()

In [10]:
bot_voies_algn1 = bottins.join(voies.set_index("L_LONGMIN"), on="Rue")
bot_voies_algn2 = bottins.join(voies.set_index("L_VOIE"), on="Rue")
bot_voies_algn3 = bottins.join(voies.set_index("L_COURTMIN"), on="Rue")

In [11]:
# see how many streets were aligned
print(bot_voies_algn1["Geometry"].isna().sum())
print(bot_voies_algn2["Geometry"].isna().sum())
print(bot_voies_algn3["Geometry"].isna().sum())

4228735
3191199
3793594

In [14]:
# start with 2nd dataframe as basis, split into aligned an not aligned data
aligned = bot_voies_algn2.loc[bot_voies_algn2["Geometry"].notna()]
not_aligned = bot_voies_algn2.loc[bot_voies_algn2["Geometry"].isna()]
not_aligned = not_aligned.drop(["N_SQ_VO", "L_COURTMIN", "L_LONGMIN", "Geometry", "LENGTH", "Geometry X Y"], axis=1)
print("aligned:", len(aligned), "not aligned:", len(not_aligned))

aligned: 1933426 not aligned: 3191199

In [15]:
# perform join with "L_COURTMIN on not_aligned dataframe"
x = not_aligned.join(voies.set_index("L_COURTMIN"), on="Rue")
aligned = aligned.append(x[x["Geometry"].notna()], ignore_index = True)
not_aligned = x[x["Geometry"].isna()]
not_aligned = not_aligned.drop(["N_SQ_VO", "L_LONGMIN", "L_VOIE", "Geometry", "LENGTH", "Geometry X Y"], axis=1)
print("aligned:", len(aligned), "not aligned:", len(not_aligned))

aligned: 2545967 not aligned: 2578666

In [16]:
# perform join with "L_LONGMIN on not_aligned dataframe"
x = not_aligned.join(voies.set_index("L_LONGMIN"), on="Rue")
aligned = aligned.append(x[x["Geometry"].notna()], ignore_index = True)
not_aligned = x[x["Geometry"].isna()]
print("aligned:", len(aligned), "not aligned:", len(not_aligned))

aligned: 2713723 not aligned: 2410910

In [17]:
not_aligned.tail()

,Unnamed: 0,page,row,Nom,Métier,Rue,Numéro,annee,N_SQ_VO,L_VOIE,L_COURTMIN,Geometry,LENGTH,Geometry X Y
4406148,bpt6k9780089g,1607,235,Zvang,blanchiss.,r. jules-vallès,5.,1922,NaN,NaN,NaN,NaN,NaN,NaN
4406153,bpt6k9780089g,1607,246,Zweiger (Vve),vins-restaur.,r. des hospitalières-st-gervais,12.,1922,NaN,NaN,NaN,NaN,NaN,NaN
4406156,bpt6k9780089g,1607,252,Zwilling,déchets de cuir,r. de buffon,67.,1922,NaN,NaN,NaN,NaN,NaN,NaN
4406157,bpt6k9780089g,1607,254,Zwinger (Henri),agent de fabriques,faub. poissonnière,65.,1922,NaN,NaN,NaN,NaN,NaN,NaN
4406162,bpt6k9780089g,1607,263,Zyssmann,bar,r. de pivoli,40.,1922,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Count how many addresses were aligned per year
annee_aligned = aligned.groupby(by=["annee"]).count()[["Nom"]]
annee_not_aligned = not_aligned.groupby(by=["annee"]).count()[["Nom"]]
df_per_year = annee_aligned.join(annee_not_aligned, lsuffix='_aligned', rsuffix='_not_aligned')

In [19]:
# Calculate the ratio of aligned addresses
df_per_year["ratio_aligned"] = df_per_year["Nom_aligned"] / (df_per_year["Nom_aligned"]+df_per_year["Nom_not_aligned"])
df_per_year

       Nom_aligned  Nom_not_aligned  ratio_aligned
annee
1839         17685            25795       0.406739
1841         21159            29352       0.418899
1842         22031            30303       0.420969
1843         18823            26673       0.413729
1844         21385            28703       0.426949
1845         22232            29422       0.430402
1846         23083            30404       0.431563
1847         23829            32053       0.426416
1848         26562            34287       0.436523
1849         26428            32924       0.445276
1850         27337            32000       0.460707
1851         28994            32625       0.470537
1852         31240            32718       0.488446
1853         32018            33871       0.485938
1854         34833            35458       0.495554
1855         36281            36926       0.495595
1856         37701            37776       0.499503
1857         37487            38901       0.490745
1858         37177            39172       0.486935
1859         35117            38937       0.474208
1860         37987            44767       0.459035
1861         38842            46152       0.456997
1862         40636            48689       0.454923
1863         40668            49484       0.451105
1864         37202            50034       0.426452
1870         55608            47271       0.540518
1871         55071            44074       0.555459
1873         55070            43888       0.556499
1874         54769            44009       0.554466
1875         59450            46133       0.563064
1876         60230            46359       0.565068
1877         62220            47632       0.566398
1878         64567            47503       0.576131
1879         63055            47867       0.568463
1880         64040            47286       0.575247
1881         70860            50842       0.582242
1882         68790            48912       0.584442
1883         75270            51635       0.593121
1884         71889            49729       0.591105
1885         75353            52474       0.589492
1886         77132            53776       0.589208
1887         66956            52500       0.560508
1888         66144            51735       0.561118
1890         64456            49419       0.566024
1893         69265            49890       0.581302
1894         65005            51176       0.559515
1896         58246            53354       0.521918
1897         60376            53406       0.530629
1898         63626            53997       0.540932
1900         66023            54427       0.548136
1901         67716            54907       0.552229
1907         68370            53484       0.561081
1914         69386            54134       0.561739
1921         64722            53957       0.545353
1922         73321            57708       0.559578

In [28]:
aligned.tail()

,Unnamed: 0,page,row,Nom,Métier,Rue,Numéro,annee,N_SQ_VO,L_COURTMIN,L_LONGMIN,Geometry,LENGTH,Geometry X Y,L_VOIE
2713718,bpt6k9780089g,1603,137,Woog (H.),courtier en march.,square la bruyère,2. (90). T. Trud. 12. 99.,1922,750004615.0,sq. la bruyère,NaN,"{""coordinates"": [[2.333247399796023, 48.879067...",49.933780,"48.87912453518579,2.332918048991286",la bruyere
2713719,bpt6k9780089g,1604,273,Yseux,relieur,quai de conti,7.,1922,750004871.0,qu. de conti,NaN,"{""coordinates"": [[[2.3404337067044763, 48.8560...",337.957721,"48.856973688745086,2.3388802711013708",conti
2713720,bpt6k9780089g,1604,305,Yver,boucher en gros,quai de l'oise,41.,1922,750005209.0,qu. de l'oise,NaN,"{""coordinates"": [[[2.379696366149043, 48.88877...",732.327618,"48.89065442303185,2.38319691672075",oise
2713721,bpt6k9780089g,1605,47,Yvoré,vétérinaire et maréchal-ferrant,quai de jemmapes,112.,1922,750003292.0,qu. de jemmapes,NaN,"{""coordinates"": [[[2.367392608119634, 48.86876...",1922.227007,"48.876028316605066,2.3665121066795267",jemmapes
2713722,bpt6k9780089g,1605,106,Zadok (Dr),médecin,square moncey,3.,1922,750004558.0,sq. moncey,NaN,"{""coordinates"": [[[2.3306447263897896, 48.8800...",143.281994,"48.88052926002643,2.3305025235547654",moncey

In [27]:
aligned["Rue"]

0                   provence
1                   provence
2                       isly
3                castiglione
4                     temple
                 ...
2713718    square la bruyère
2713719        quai de conti
2713720       quai de l'oise
2713721     quai de jemmapes
2713722        square moncey
Name: Rue, Length: 2713723, dtype: object

In [33]:
from Levenshtein import distance as lev

## Paris Opendata - Adresses

In [31]:
adresses = pd.read_csv("data/opendata_adresse_paris.csv", sep=";")

In [21]:
adresses.head()
# N_SQ_VO same as with voies!

,Geometry X Y,Geometry,N_SQ_AD,N_VOIE,C_SUF1,C_SUF2,C_SUF3,C_AR,A_NVOIE,B_ANGLE,B_OFFSTDF,B_AFFSTDF,B_HORS75,L_NVOIE,L_ADR,N_SQ_AR,N_SQ_VO,OBJECTID
0,"48.868149964330925,2.385363237327124","{""coordinates"": [2.385363237327124, 48.8681499...",750088825,31.0,NaN,NaN,NaN,20.0,21.0,N,O,NaN,N,31,31 RUE ETIENNE DOLET,750000020.0,750003581.0,48975
1,"48.873918224142145,2.308770442174867","{""coordinates"": [2.308770442174867, 48.8739182...",750038510,2.0,NaN,NaN,NaN,8.0,222.0,O,O,NaN,N,2,2 RUE PAUL CEZANNE,750000008.0,750004449.0,48990
2,"48.84631684220949,2.34848334292492","{""coordinates"": [2.34848334292492, 48.84631684...",750162012,14.0,NaN,NaN,NaN,5.0,346.0,N,O,NaN,N,14,14 RUE CLOVIS,750000005.0,750004930.0,49022
3,"48.850519497345935,2.3857899214565674","{""coordinates"": [2.3857899214565674, 48.850519...",750054032,31.0,b,NaN,NaN,11.0,359.0,N,O,NaN,N,31b,31b RUE DE MONTREUIL,750000011.0,750003059.0,49026
4,"48.85233571571768,2.2684341614185204","{""coordinates"": [2.2684341614185204, 48.852335...",750128612,47.0,NaN,NaN,NaN,16.0,124.0,O,O,NaN,N,47,47 RUE RIBERA,750000016.0,750000897.0,49033

In [22]:
adresses[["Numéro", "Rue"]] = adresses["L_ADR"].str.split(" ", 1, expand=True)
adresses["Rue"] = adresses["Rue"].str.lower()
adresses.head()

,Geometry X Y,Geometry,N_SQ_AD,N_VOIE,C_SUF1,C_SUF2,C_SUF3,C_AR,A_NVOIE,B_ANGLE,B_OFFSTDF,B_AFFSTDF,B_HORS75,L_NVOIE,L_ADR,N_SQ_AR,N_SQ_VO,OBJECTID,Numéro,Rue
0,"48.868149964330925,2.385363237327124","{""coordinates"": [2.385363237327124, 48.8681499...",750088825,31.0,NaN,NaN,NaN,20.0,21.0,N,O,NaN,N,31,31 RUE ETIENNE DOLET,750000020.0,750003581.0,48975,31,rue etienne dolet
1,"48.873918224142145,2.308770442174867","{""coordinates"": [2.308770442174867, 48.8739182...",750038510,2.0,NaN,NaN,NaN,8.0,222.0,O,O,NaN,N,2,2 RUE PAUL CEZANNE,750000008.0,750004449.0,48990,2,rue paul cezanne
2,"48.84631684220949,2.34848334292492","{""coordinates"": [2.34848334292492, 48.84631684...",750162012,14.0,NaN,NaN,NaN,5.0,346.0,N,O,NaN,N,14,14 RUE CLOVIS,750000005.0,750004930.0,49022,14,rue clovis
3,"48.850519497345935,2.3857899214565674","{""coordinates"": [2.3857899214565674, 48.850519...",750054032,31.0,b,NaN,NaN,11.0,359.0,N,O,NaN,N,31b,31b RUE DE MONTREUIL,750000011.0,750003059.0,49026,31b,rue de montreuil
4,"48.85233571571768,2.2684341614185204","{""coordinates"": [2.2684341614185204, 48.852335...",750128612,47.0,NaN,NaN,NaN,16.0,124.0,O,O,NaN,N,47,47 RUE RIBERA,750000016.0,750000897.0,49033,47,rue ribera